### ISSUE TITLE
XCode Tools

### ISSUE THREAD

**Issue by apbendi** [ascensionpress/dotfiles#1]
So if you don't have the latest version of XCode command line tools installed, you'll run into problems later in the process when building certain gems with native extensions.

The command that needs to be run is `xcode-select --install` but this then pops up a GUI to agree to the EULA and requires a couple of clicks to get through. Should we put this command in the `brew.sh` script anyway?

Thoughs @iloveitaly & @davidlaprade ?

**Comment by iloveitaly** [comment]
This is noted in the dotfile readme: https://github.com/ascensionpress/dotfiles#installation
