### ISSUE TITLE
fix apache restart

### ISSUE THREAD

**Issue by iloveitaly** [ascensionpress/dotfiles#4]
on computer startup we have to run `sudo killall httpd; killall httpd; sudo apachectl` to get apache running

* we need to disable apache startup from the std os x startup
* need to run `sudo apachectl` on startup in some automated fashion

**Comment by jochambo** [comment]
@twhite59 I know you had some ideas on how to fix this in the dotfiles.

**Comment by davidlaprade** [comment]
Closed with 8fbf8a9...a1f9336
